export const speakers = [
    {
        name: "Dr. Sanjay Arora",
        about: "Founder & CEO at Shells Advertising",
        // insta: "https://www.instagram.com/sanjayaroraofficial/",
        // linkedin: "https://www.linkedin.com/in/drsanjayarora/",
        // facebook: "https://www.facebook.com/chiefsanjayarora/",
        image: "/assets/HomePage/HorizontalScroll/pastSpeaker/Sanjay_Arora.png",
    },
    {
        name: "Dr. Gajendra Purohit",
        about: "Founder and CEO of Mathscare",
        // insta: "https://www.instagram.com/dr.gajendrapurohit/",
        // linkedin: "https://www.linkedin.com/in/dr-gajendra-purohit-123456789/",
        // facebook: "https://www.facebook.com/drgajendra.purohit/",
        image: "/assets/HomePage/HorizontalScroll/pastSpeaker/Gajendra_purohit.png",
    },
    {
        name: "Ms. Roshni Chhabra",
        about: "Senior Success Manager at Sprinklr",
        // insta: "https://www.instagram.com/roshnichhabra/",
        // linkedin: "https://www.linkedin.com/in/roshnichhabra/",
        // facebook: "https://www.facebook.com/roshni.chhabra",
        image: "/assets/HomePage/HorizontalScroll/pastSpeaker/Roshni_Chhabra.png",
    },
    {
        name: "Ms. Keerti Purswani",
        about: "Founder of Educosys",
        // insta: "https://www.instagram.com/keertipurswani/",
        // linkedin: "https://www.linkedin.com/in/keertipurswani/",
        // facebook: "https://www.facebook.com/keerti.purswani",
        image: "/assets/HomePage/HorizontalScroll/pastSpeaker/Keerti_Purswani.png",
    },
    {
        name: "Mr. Abhishek Mungoli",
        about: "Data Scientist at InMobi, an AdTech firm",
        // insta: "https://www.instagram.com/abhishekmungoli/",
        // linkedin: "https://www.linkedin.com/in/abhishekmungoli/",
        // facebook: "https://www.facebook.com/abhishek.mungoli",
        image: "/assets/HomePage/HorizontalScroll/pastSpeaker/Abhishek_Mungoli.png",
    },
];
